# Generated from C:\photoCAD\layout1002\AMFpdk_3_5_Cband_0420_3.5_Cband\technology\layers.csv

from fnpcell.pdk.technology.all import Layer, LayerEnum, Process, ProcessEnum, Purpose, PurposeEnum

class PROCESS(ProcessEnum):
    AMARK = Process(0, 'AMARK')
    RIB_WG = Process(10, 'RIB_WG')
    GRAT_WG = Process(11, 'GRAT_WG')
    SLAB_WG = Process(12, 'SLAB_WG')
    PP = Process(20, 'PP')
    PCONT = Process(21, 'PCONT')
    NCONT = Process(22, 'NCONT')
    PIM = Process(23, 'PIM')
    NIM = Process(24, 'NIM')
    IPD = Process(25, 'IPD')
    IND = Process(26, 'IND')
    GeEP = Process(40, 'GeEP')
    NPPGE = Process(41, 'NPPGE')
    SINWIN1 = Process(53, 'SINWIN1')
    SINWG1 = Process(54, 'SINWG1')
    SINWINREV1 = Process(55, 'SINWINREV1')
    VIA1 = Process(100, 'VIA1')
    MT1 = Process(105, 'MT1')
    MT1R = Process(106, 'MT1R')
    HTR = Process(115, 'HTR')
    VIA2 = Process(120, 'VIA2')
    MT2 = Process(125, 'MT2')
    PAD = Process(150, 'PAD')
    OXOP = Process(151, 'OXOP')
    DT = Process(160, 'DT')
    BLACKBOX = Process(1001, 'BLACKBOX')
    BB_LABEL = Process(1002, 'BB_LABEL')
    BB_OP_SI = Process(1010, 'BB_OP_SI')
    BB_OP_SIN = Process(1011, 'BB_OP_SIN')
    BB_OP_FB = Process(1012, 'BB_OP_FB')
    BB_EP = Process(1020, 'BB_EP')
    BB_MT1 = Process(1021, 'BB_MT1')
    BB_MT2 = Process(1022, 'BB_MT2')
    EXCL_DRC = Process(2000, 'EXCL_DRC')
    LBL = Process(200, 'LBL')
    MARKER = Process(201, 'MARKER')
    BLACK_FP = Process(202, 'BLACK_FP')

class PURPOSE(PurposeEnum):
    DRW = Purpose(0, 'DRW')
    GEN = Purpose(4, 'GEN')

class LAYER(LayerEnum):
    AMARK = Layer(PROCESS.AMARK, PURPOSE.DRW, 'Alignment mark')
    RIB = Layer(PROCESS.RIB_WG, PURPOSE.DRW, 'RIB WG etch 70nm')
    GRAT = Layer(PROCESS.GRAT_WG, PURPOSE.DRW, 'GC WG etch 60nm')
    SLAB = Layer(PROCESS.SLAB_WG, PURPOSE.DRW, 'SLAB WG etch 90nm')
    PP = Layer(PROCESS.PP, PURPOSE.DRW, 'P+ on SiGe PD ')
    PCONT = Layer(PROCESS.PCONT, PURPOSE.DRW, 'P++ on Si for Ohmic contact/90nm')
    NCONT = Layer(PROCESS.NCONT, PURPOSE.DRW, 'N++ on Si for Ohmic contact/90nm')
    PIM = Layer(PROCESS.PIM, PURPOSE.DRW, 'P for modulator/220nm')
    NIM = Layer(PROCESS.NIM, PURPOSE.DRW, 'N for modulator/220nm')
    IPD = Layer(PROCESS.IPD, PURPOSE.DRW, 'intermediate P doping')
    IND = Layer(PROCESS.IND, PURPOSE.DRW, 'intermediate N doping')
    GeEP = Layer(PROCESS.GeEP, PURPOSE.DRW, 'Germanium epitaxy 500nm')
    NPPGE = Layer(PROCESS.NPPGE, PURPOSE.DRW, 'N++ Ge epi for upper contact')
    SINWIN1 = Layer(PROCESS.SINWIN1, PURPOSE.DRW, 'SiN Windows 1')
    SINWG1 = Layer(PROCESS.SINWG1, PURPOSE.DRW, 'PECVD SiN waveguide 1')
    SINWINREV1 = Layer(PROCESS.SINWINREV1, PURPOSE.DRW, '(Typically generated) SiN Windows 1 reverse')
    VIA1 = Layer(PROCESS.VIA1, PURPOSE.DRW, 'VIA1 to Si/Ge')
    MT1 = Layer(PROCESS.MT1, PURPOSE.DRW, 'Metal 1 750nm')
    MT1R = Layer(PROCESS.MT1R, PURPOSE.DRW, '(Typically generated) Metal 1 reverse and planarization')
    HTR = Layer(PROCESS.HTR, PURPOSE.DRW, 'Heater TiN 120nm')
    VIA2 = Layer(PROCESS.VIA2, PURPOSE.DRW, 'VIA2 to HTR & MT1')
    MT2 = Layer(PROCESS.MT2, PURPOSE.DRW, 'Metal 2000nm')
    PAD = Layer(PROCESS.PAD, PURPOSE.DRW, 'Pad Open')
    OXOP = Layer(PROCESS.OXOP, PURPOSE.DRW, 'Oxide Open to expose passive devices')
    DTR = Layer(PROCESS.DT, PURPOSE.DRW, 'Deep trench')
    TR = Layer(PROCESS.RIB_WG, PURPOSE.GEN, ' dummy fill for RIB WG')
    TM1 = Layer(PROCESS.MT1, PURPOSE.GEN, ' dummy fill for Metal 1')
    BLACKBOX = Layer(PROCESS.BLACKBOX, PURPOSE.DRW, 'BLACKBOX Boundary')
    BB_LABEL = Layer(PROCESS.BB_LABEL, PURPOSE.DRW, 'BLACKBOX text')
    BB_OP_SI = Layer(PROCESS.BB_OP_SI, PURPOSE.DRW, 'BLACKBOX Optical Ports for Si')
    BB_OP_SIN = Layer(PROCESS.BB_OP_SIN, PURPOSE.DRW, 'BLACKBOX Optical Ports for SiN')
    BB_OP_FB = Layer(PROCESS.BB_OP_FB, PURPOSE.DRW, 'BLACKBOX Optical Ports for Fiber')
    BB_EP = Layer(PROCESS.BB_EP, PURPOSE.DRW, 'BLACKBOX Electrical Ports')
    BB_MT1 = Layer(PROCESS.BB_MT1, PURPOSE.DRW, 'BLACKBOX Electrical Ports for Metal 1')
    BB_MT2 = Layer(PROCESS.BB_MT2, PURPOSE.DRW, 'BLACKBOX Electrical Ports for Metal 2')
    EXCL_DRC = Layer(PROCESS.EXCL_DRC, PURPOSE.DRW, 'DRC exclusion layer')
    LBL = Layer(PROCESS.LBL, PURPOSE.DRW, 'label')
    MARKER = Layer(PROCESS.MARKER, PURPOSE.DRW, 'Text layer, not to print on wafer')
    BLACK_FP = Layer(PROCESS.BLACK_FP, PURPOSE.DRW, 'Design outline(for IP device)')
