# Generated from C:\photoCAD\layout1002\IMECAS_pdk\technology\layers.csv

from fnpcell.pdk.technology.all import Layer, LayerEnum, Process, ProcessEnum, Purpose, PurposeEnum


class PROCESS(ProcessEnum):
    FE = Process(10, 'Full etch')
    SE = Process(11, 'Shallow etch')
    ME = Process(12, 'Medium etch')
    SINSL = Process(39, 'SiN stop-layer etching')
    PL = Process(21, 'P type light doping')
    NL = Process(22, 'N type light doping')
    PM = Process(23, 'P type moderate doping')
    NM = Process(24, 'N type moderate doping')
    PH = Process(25, 'P type high doping')
    NH = Process(26, 'N type high doping')
    GP = Process(41, 'P type high doping on Ge')
    GN = Process(42, 'N type high doping on Ge')
    PCON = Process(9, 'Hole to Si layer')
    GEPCON = Process(7, 'Hole to Ge layer')
    GE = Process(40, 'Ge epitaxy')
    PY1 = Process(103, '150nm Poly-Si etch')
    PY2 = Process(104, '150nm Poly-Si + 70nm Si etch')
    M1 = Process(31, 'Metal 1')
    TIN = Process(34, 'TiN Metal heater')
    PAD = Process(36, 'Passivation window')
    LP = Process(90, 'GC open window')
    DETCH = Process(80, '120um deep etch')
    MARK = Process(100, 'Device recognition')
    BB = Process(120, 'Define design boundary')
    DOC = Process(1000, 'Only for layout recognization, will not appear on mask')
    PINREC = Process(1002, 'Port recognization')
    FLYLINE = Process(91, 'Fly line')
    ERROR = Process(92, 'Error')


class PURPOSE(PurposeEnum):
    COR = Purpose(2, 'Waveguide core')
    CLD = Purpose(3, 'Waveguide cladding')
    TRE = Purpose(4, 'Waveguide trench')
    DRW = Purpose(0, 'Drawing')
    MARK = Purpose(35, 'Mark')


class LAYER(LayerEnum):
    FECOR = Layer(PROCESS.FE, PURPOSE.COR, '220nm Full Etch waveguide core')
    FECLD = Layer(PROCESS.FE, PURPOSE.CLD, '220nm Full Etch waveguide cladding')
    FETCH = Layer(PROCESS.FE, PURPOSE.TRE, '220nm Full Etch waveguide trench')
    SECOR = Layer(PROCESS.SE, PURPOSE.COR, '70nm Shallow Etch waveguide core')
    SECLD = Layer(PROCESS.SE, PURPOSE.CLD, '70nm Shallow Etch waveguide cladding')
    SETCH = Layer(PROCESS.SE, PURPOSE.TRE, '70nm Shallow Etch waveguide trench')
    MECOR = Layer(PROCESS.ME, PURPOSE.COR, '150nm Medium Etch waveguide core')
    MECLD = Layer(PROCESS.ME, PURPOSE.CLD, '150nm Medium Etch waveguide cladding')
    METCH = Layer(PROCESS.ME, PURPOSE.TRE, '150nm Medium Etch waveguide trench')
    SINSL = Layer(PROCESS.SINSL, PURPOSE.DRW, 'SiN stop-layer etching')
    PL = Layer(PROCESS.PL, PURPOSE.DRW, 'P type light doping')
    NL = Layer(PROCESS.NL, PURPOSE.DRW, 'N type light doping')
    PM = Layer(PROCESS.PM, PURPOSE.DRW, 'P type moderate doping')
    NM = Layer(PROCESS.NM, PURPOSE.DRW, 'N type moderate doping')
    PH = Layer(PROCESS.PH, PURPOSE.DRW, 'P type high doping')
    NH = Layer(PROCESS.NH, PURPOSE.DRW, 'N type high doping')
    GP = Layer(PROCESS.GP, PURPOSE.DRW, 'P type high doping on Ge')
    GN = Layer(PROCESS.GN, PURPOSE.DRW, 'N type high doping on Ge')
    PCON = Layer(PROCESS.PCON, PURPOSE.DRW, 'Hole to Si layer')
    GEPCON = Layer(PROCESS.GEPCON, PURPOSE.DRW, 'Hole to Ge layer')
    GE = Layer(PROCESS.GE, PURPOSE.DRW, 'Germanium epitaxy')
    PY1 = Layer(PROCESS.PY1, PURPOSE.DRW, '150nm Poly-Si etch')
    PY2 = Layer(PROCESS.PY2, PURPOSE.DRW, '150nm Poly-Si + 70nm Si etch')
    M1 = Layer(PROCESS.M1, PURPOSE.DRW, 'Metal 1')
    TIN = Layer(PROCESS.TIN, PURPOSE.DRW, 'TiN heater')
    PAD = Layer(PROCESS.PAD, PURPOSE.DRW, 'Passivation window')
    LP = Layer(PROCESS.LP, PURPOSE.DRW, 'GC open window')
    DETCH = Layer(PROCESS.DETCH, PURPOSE.DRW, '120um deep etch')
    MARK = Layer(PROCESS.MARK, PURPOSE.DRW, 'Device recognition')
    BB = Layer(PROCESS.BB, PURPOSE.DRW, 'Define design boundary')
    DOC = Layer(PROCESS.DOC, PURPOSE.DRW, 'Only for layout recognization, will not appear on mask')
    PINREC = Layer(PROCESS.PINREC, PURPOSE.DRW, 'Port recognization')
    FLYLINE_MARK = Layer(PROCESS.FLYLINE, PURPOSE.MARK, 'Flyline for insufficient space in AutoLink')
    ERROR_MARK = Layer(PROCESS.ERROR, PURPOSE.MARK, 'Error mark')
